### ISSUE TITLE
invalid client

### ISSUE THREAD

**Issue by panneertealorca** [marshmallow-packages/zoho-desk#20]
I have followed the steps. but i got this issue always
![zoho-desk-png-740×494-](https://user-images.githubusercontent.com/70587411/127327414-6b99ac0a-4185-4ee2-aa8f-86dbfaf3b856.png)

**Comment by stefvanesch** [comment]
@panneertealorca did you change the `config/zoho.php`? You should enter your credentials there, or even better, set the `ZOHO_CLIENT_ID` and `ZOHO_CLIENT_SECRET` env variables. We just had the same issue and we forgot to do this so maybe this is your issue as well?

**Comment by stefvanesch** [comment]
@panneertealorca did you change the `config/zoho.php`? You should enter your credentials there, or even better, set the `ZOHO_CLIENT_ID` and `ZOHO_CLIENT_SECRET` env variables. We just had the same issue and we forgot to do this so maybe this is your issue as well?

**Comment by fecosta90** [comment]
@panneertealorca , maybe your zoho account running on US server, so you need to publish config file as @stefvanesch said and change .ENV file. Setting this:

ZOHO_AUTH_HOST=https://accounts.zoho.com/oauth/v2
ZOHO_DESK_HOST=https://desk.zoho.com/api/v1

**Comment by Mood-al** [comment]
hey guys from where can i get the temporary code? 
as i understood i must send a post request to this endpoint `https://accounts.zoho.com/oauth/v2/auth
?response_type=code&
client_id=1000.GMB0YULZHJK411284S8I5GZ4CHUEX0&
scope=AaaServer.profile.Read&
redirect_uri=https://www.zylker.com/oauthredirect&
prompt=consent` to get it am i right? I got this endpoint from here https://www.zoho.com/accounts/protocol/oauth/web-apps/authorization.html
so how should i do that manually by postman or should i create a function to do that for me

sorry for my questions but i'm so new to laravel and i feel lost
