### ISSUE TITLE
Example adding attachment into a Ticket

### ISSUE THREAD

**Issue by fecosta90** [marshmallow-packages/zoho-desk#21]
Hey, i've tried so many ways to send attachments into Ticket, but no progress here.
Can u guys help me with an example?

**Comment by stefvanesch** [comment]
Doesn't the example in the readme work for you?

```php
Ticket::attachment($ticket_id, $path);
```

Do you get any errors?

**Comment by fecosta90** [comment]
hey @stefvanesch, sorry for wasting your time.

I opened the function that sends the attachment, and I noticed that it uses the storage_path function.
My file was being saved elsewhere. So I made the proper correction of the path to be used

 $relative_path = 'app/public/'.$filePath;  => now your function reads /var/www/application/storage/app/public/uploads/file.png
 
 
 Thank you.

**Comment by stefvanesch** [comment]
@fecostadesousa no time was wasted! If you have any questions just let us know. Will update the package to make this usage more clear.
