### ISSUE TITLE
Can't use package to get All help center APIs

### ISSUE THREAD

**Issue by fecosta90** [marshmallow-packages/zoho-desk#22]
When Helpdesk Team uses Knowledge Base as a portal, the endpoint to get articles, categories, etc is different.

Examples:
GET /portal/api/kbArticles
GET /portal/api/kbArticles/{articles_id}

Ref: https://desk.zoho.eu/portal/APIDocument.do#KnowledgeBase

We need to check what endpoint we're using before do GET/POST/PATCH.
I'll submit and example, hope it helps.

Thank you

**Comment by stefvanesch** [comment]
@fecostadesousa thanks man! We will look in to this later today and merge your pull request.

**Comment by stefvanesch** [comment]
The portal api is implementend. Thanks @fecostadesousa for your pull request. We fixed it a little different. You can call a portal method on the ZohoDesk Facade to "activate" the portal api.

```php
ZohoDesk::portal()->get('kbArticles/{articles_id});
```
