### ISSUE TITLE
The OAuth Token does not contain the scope to perform this operation.

### ISSUE THREAD

**Issue by Mood-al** [marshmallow-packages/zoho-desk#26]
Hey guys when I'm runing this command to get the department id `php artisan zoho-desk:list-departments`

this error is happening 
![image](https://user-images.githubusercontent.com/63562308/154828073-d71f82d4-fc43-4a70-93d4-a531feaf8ac9.png)
 do you have any idea why this is happeing? 
inside my db the refresh token and the acceses tokens are stored so how i can pass the scrope to get the id of the department

**Comment by stefvanesch** [comment]
@Mood-al sorry for the late reply. We don't experience this issue. Are you still having this problem?
